name: Laravel CI

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  laravel:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./mims-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, pdo_sqlite, sqlite3

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Run Laravel tests
        run: php artisan test
